### ISSUE TITLE
Program does not open with Zen 3 CPU

### ISSUE THREAD

**Issue by ssateneth** [irusanov/ZenTimings#7] opened 2020-11-07 21:00 UTC
Freshly installed on Windows 10 Pro for Workstations (ver 2004) with ryzen chipset drivers 2.10.13.408 and ryzen master 2.6.0.1692 installed, latest windows updates installed (I did not opt in to using 20H2). Ryzen 9 5950X + MSI MEG X570 GODLIKE board with version 7C34v1B BIOS (AGESA ComboAm4v2PI 1.1.0.0 Patch C)

Using ZenTimings 1.2.0, tried running both programs and running as admin, the program will not open. The new version (not legacy) will show a "ZenTimings" splash screen for about a second before disappearing then nothing and the program terminates according to task manager.

The windows event viewer shows 3 events when the program crashes out.

```
Application: ZenTimings.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotImplementedException
   at ZenStates.GetMaintainedSettings.GetByType(CPUType)
   at ZenStates.Ops..ctor()
   at ZenTimings.MainWindow..ctor()

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at ZenTimings.App.Main()
```

```
Faulting application name: ZenTimings.exe, version: 1.2.0.29, time stamp: 0xe5c02e1c
Faulting module name: KERNELBASE.dll, version: 10.0.19041.572, time stamp: 0x1183946c
Exception code: 0xe0434352
Fault offset: 0x0000000000023e49
Faulting process id: 0x1e04
Faulting application start time: 0x01d6b5491ca402c6
Faulting application path: C:\Users\User\Desktop\ZenTimings\ZenTimings.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: dfda32d4-9349-4aaf-8dd9-6a2e592a7e91
Faulting package full name: 
Faulting package-relative application ID:
```

```
Fault bucket 1506868277683990495, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: ZenTimings.exe
P2: 1.2.0.29
P3: e5c02e1c
P4: Common
P5: 1.0.0.0
P6: b69a908f
P7: 57
P8: 14
P9: System.Windows.Markup.XamlParse
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCC0E.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCCDA.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCCDB.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCCED.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCCFD.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_ZenTimings.exe_9c479cbcefb7e594e803cb641d8f387236d1e_974c24d5_d3d7d3f3-570a-49ea-a2df-a4388bbeb41a

Analysis symbol: 
Rechecking for solution: 0
Report Id: dfda32d4-9349-4aaf-8dd9-6a2e592a7e91
Report Status: 268435456
Hashed bucket: 606d25ec99de46e884e978b6fea8afdf
Cab Guid: 0
```

**Comment by irusanov** [comment] 2020-11-08 19:12
There's a beta build that should work on Zen3. Will release a new version soon.
[ZenTimings_v1.2.1.65_beta2.zip](https://github.com/irusanov/ZenTimings/files/5507009/ZenTimings_v1.2.1.65_beta2.zip)

**Comment by ssateneth** [comment] 2020-11-08 19:38
Thanks. Here's some debug reports if you need them. Looks like CLDO VDDP and VDDP are not being detected at all.

![ZenTimings_Screenshot](https://user-images.githubusercontent.com/2127021/98482537-b8f1e080-21c7-11eb-8054-abb12ff37227.png)


[Debug_Report_26747728.7218916.txt](https://github.com/irusanov/ZenTimings/files/5507045/Debug_Report_26747728.7218916.txt)
[Debug_Report_26747736.3443513.txt](https://github.com/irusanov/ZenTimings/files/5507046/Debug_Report_26747736.3443513.txt)

**Comment by xAeryn** [comment] 2020-11-09 07:33
"Looks like CLDO VDDP and VDDP are not being detected at all."

I have this too, likely because they moved the sensors around - i see "CLDO VDDG IOD" and "CLDO VDDG CCD" seperately in Ryzen Master now.

**Comment by irusanov** [comment] 2020-11-09 08:41
Yes, there's support for the separate VDDG voltages now.
You can check if the values at offsets at 228 and 22C from the Power Table in the report match the VDDG voltages.
First one should be IOD, second one - CCD.

**Comment by xAeryn** [comment] 2020-11-09 08:59
I have both set the same at the moment and they match but there are a few others reading similar numbers

CLDO_VDDP also maybe at 224

**Comment by irusanov** [comment] 2020-11-09 10:02
Yes, VDDP is 224. At least that's what I have confirmed with other users, but more reports won't hurt.

**Comment by Xerxes-2** [comment] 2020-11-10 11:52
![image](https://user-images.githubusercontent.com/35587143/98670674-fe600a80-238d-11eb-85fc-66295b11f0c8.png)
M/F/UCLK is 0 in my system. VDDP and VDDGs also N/A.

**Comment by irusanov** [comment] 2020-11-10 11:58
Yes, that is expected.
Here's the version that will be released on the site today, you can test it before that.

[ZenTimings_v1.2.1.zip](https://github.com/irusanov/ZenTimings/files/5517040/ZenTimings_v1.2.1.zip)

**Comment by Xerxes-2** [comment] 2020-11-10 12:02
All timings and voltages are fine now, thx.

**Comment by irusanov** [comment] 2020-11-10 12:04
Thanks for the report. It was a stupid mistake - one line missing and the whole table was not processed at all.

**Comment by Xerxes-2** [comment] 2020-11-10 12:11
BTW, love this UX change, feeling much more modern and lighter.

**Comment by xAeryn** [comment] 2020-11-10 19:20
All good now thanks

**Closed** 2020-11-13 21:02 UTC
