### ISSUE TITLE
could not get power table

### ISSUE THREAD

**Issue by b1tbucket** [irusanov/ZenTimings#19] opened 2021-04-15 03:27 UTC
![image](https://user-images.githubusercontent.com/53288599/114809693-02390280-9dee-11eb-920d-f80fcc635712.png)

AMD Ryzen 3 3100/MAG X570 Tomahawk (MS-7C84)/BIOS 1.63/SMU 46.70.0/ComboAM4PIV2 1.2.0.2

**Comment by irusanov** [comment] 2021-04-15 17:28
I would need some more information.

- Does it refresh at some point after clicking "OK"?
  If the power table cannot be read, then fclk, mclk and uclk will be empty, along with vddp and vddg voltages.
  If they show up at some point, then something else is blocking the app from accessing the power table when launched.
- Does it happen every time?
- Do other tools, such as hwinfo, show the usual information?
- Are some other tools running at the same time?
- A debug report would also be helpful

Thanks!

**Comment by k1rOuX** [comment] 2021-04-21 20:33
Hi, I have the same issue, 
- after click ok it doesn't refresh, only 3 voltage are missing MCLK, FCLK and UCLK are correctly displayed.
- It happen everytime.
- other tools are working (HWinfo64)
- nothing else running, I like minimalist boot settings. 

My config: Ryzen r5 3600 - MSI x470 Gaming Pro Max (bios up-to-date with agesa 1.2.0.2) - ram 2x8gb GSkill Trident Z Neo

![02](https://user-images.githubusercontent.com/34191025/115617278-86f5b600-a2f1-11eb-92c9-8f76f09a2f8f.png)
![01](https://user-images.githubusercontent.com/34191025/115617279-878e4c80-a2f1-11eb-934c-9725025ddffd.png)
[Debug_Report_26983950,2393232.txt](https://github.com/irusanov/ZenTimings/files/6353756/Debug_Report_26983950.2393232.txt)

**Comment by irusanov** [comment] 2021-04-22 12:59
It seems to be AGESA 1.2.0.2 related (and maybe MSI).
The issue is current version of the app checks if first value is 0 (zero) and it seems that's always true with this new AGESA.
You can see that in the debug report, under "SMU: Power Table" section, Offset 000".
I've done this for performance reasons and until now it always had the PPT value at this offset.
I don't know what's wrong and why it changed with that AGESA version. Basically it means PPT is 0 (disabled)

I'm going to release a new version with a bugfix, but will now have to check if the whole table contains only zeroes, not just the first offset.

You can ignore the Error message for now, although I know it is annoying.

**Comment by k1rOuX** [comment] 2021-04-22 15:39
No prob man, thing happen. Keep up the good job😊

**Comment by k1rOuX** [comment] 2021-04-26 21:06
@irusanov  hey man, little feedback again. It seem that this issue is related to a UEFI settings, cause I just tryed to set back a setting in UEFI, in amd CBS > SoC/FCLK part, I dont remember the name rn but the description was "enable to force LCLK to run full speed, but it impact power saving"  I only have enable or auto.  Enable was what I had until now. I tryed to put back on auto,  didn't saw any change about FCLK / UCLK / MCLK , but now Zen Timing working fine and even  HWinfo64 show me more info, especially  watts and amperes, also FCLK MCLK UCLK.. I'll try to take some picture

**Comment by b1tbucket** [comment] 2021-04-26 21:26
My machines been up for a few days and I mysteriously don't get the error now either, suspeciously I havnt changed any settings in the UEFI BIOS



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by irusanov** [comment] 2021-04-26 21:54
Thanks for feedback!
I have a new beta/debug build which should not show that error.
[ZenTimings_v1.2.4.234-debug.zip](https://github.com/irusanov/ZenTimings/files/6380592/ZenTimings_v1.2.4.234-debug.zip)

**Comment by k1rOuX** [comment] 2021-04-26 22:05
okay let's try =)

**Comment by k1rOuX** [comment] 2021-04-26 22:12
@irusanov yep no error message anymore, here is the debug output if you need 
[Debug_Report_26991250,7275392.txt](https://github.com/irusanov/ZenTimings/files/6380647/Debug_Report_26991250.7275392.txt)

**Comment by k1rOuX** [comment] 2021-04-26 22:14
What ? ^^ 

![Sans titre](https://user-images.githubusercontent.com/34191025/116157594-855f3000-a6ed-11eb-9d52-8b7aeaff25a7.png)

**Comment by irusanov** [comment] 2021-04-26 23:21
That's valid for all 3600. They have 2 physical cores disabled (one from each CCX)

**Comment by b1tbucket** [comment] 2021-04-27 00:00
I can't explain it as i've not modified any settings on my end however the error is gone on the stable build (same build i used when I opened  this issue) and works fine also on the debug build even after hard power off.

I'll keep an eye out for it but perhaps we can close this issue off now.

**Comment by irusanov** [comment] 2021-04-27 00:17
I will close it when this version gets released. Thanks for cooperation, really helped me solve the issue.

**Comment by k1rOuX** [comment] 2021-04-27 00:18
@irusanov  yeah I already herad something like this, it's basically low binned 3700/3800, with core disabled. But it's the first time I see 8 core displayed in a tool ^^ I miss the good old time where we could unlock hidden cores on old AMD phenom cpu ^^ 

@b1tbucket yep it's due to this settings.  Fun fact in my bios, when I change it then press F10 to save and exit, it say I didn't change anything xD. Btw I seem to allow my fix CPU overclock to downclock a bit (from 4.5 to 4.2 at idle in task manager, no change in HWinfo64, I use the 1usmus power plan).

**Comment by windymindy** [comment] 2021-05-28 15:44
Came to let you know that disabled 'LCLK DPM' option breaks things, but k1rOuX has already sorted it out.

**Comment by irusanov** [comment] 2021-06-15 18:11
The original issue should be fixed now.

**Closed by irusanov** 2021-06-15 18:11 UTC
Labels: bug, enhancement
