### ISSUE TITLE
Can't start 1.2.4 version

### ISSUE THREAD

**Issue by roman-orekhov** [irusanov/ZenTimings#21] opened 2021-06-14 00:45 UTC
1.2.3 worked good.

After replacing files of 1.2.3 with files of 1.2.4 it won't start properly:
first start asks about autoupdate, I press "No", then it checks for updates and exits.
Second and so on starts: it checks for updates, then "CPU", then it exits.

Previously it worked like this:
![2021-06-11](https://user-images.githubusercontent.com/17900339/121826933-f3be7880-ccc2-11eb-9441-d44fead1002e.png)

**Comment by irusanov** [comment] 2021-06-14 07:25
What if you extract the new zip in a new folder and launch from there?
I have tested the exact same zip from the website directly and it works on 2 machines, but they are both with older SMU version.

**Comment by Scoty43** [comment] 2021-06-14 08:42
Same problem here. Not start and i have test also in a new folder.

**Comment by irusanov** [comment] 2021-06-14 09:39
Would you mind attaching a debug report from v1.2.3?

**Comment by Scoty43** [comment] 2021-06-14 09:41
> Would you mind attaching a debug report from v1.2.3? Thank you.

Sure here.
[Debug_Report_27061060,7511857.txt](https://github.com/irusanov/ZenTimings/files/6647306/Debug_Report_27061060.7511857.txt)

**Comment by irusanov** [comment] 2021-06-14 09:46
Thanks, nothing unusual.
Next thing to try:
- Make a copy of your working v1.2.3
- Replace ZenStates-Core.dll from v1.2.4 to the v1.2.3 directory copy

Run the old app with that new DLL and see if it starts.
I need to understand if it is from the dll or from the app itself.

**Comment by Scoty43** [comment] 2021-06-14 09:50
Dont start. See only the Bootscreen thene closing.

**Comment by irusanov** [comment] 2021-06-14 09:56
Thanks, so it seems to be from the dll then. I will have to find a way to reproduce it first.

**Comment by Scoty43** [comment] 2021-06-14 10:02
Ok thanks too.

**Comment by roman-orekhov** [comment] 2021-06-14 10:18
> What if you extract the new zip in a new folder and launch from there?
> You can also try with deleting settings.xml, it would effectively reset them, but they aren't that many to redo after that from the options dialog.
Done both -- no dice.

Report from older version:
[Debug_Report_27059072,7153857.txt](https://github.com/irusanov/ZenTimings/files/6647533/Debug_Report_27059072.7153857.txt)

Using new DLL with old version also didn't work.

**Comment by irusanov** [comment] 2021-06-14 10:24
@roman-orekhov Yes, old app is not compatible with new DLL.
I might have found the problem, there's incorrect status returned when the lib is partially initialized.

Could you try the dll with the fixed status. It was returning status 0 rather than correct 2.
It could still display some sort of an error, but allow the app to load.
[ZenStates-Core.zip](https://github.com/irusanov/ZenTimings/files/6647586/ZenStates-Core.zip)

**Comment by Scoty43** [comment] 2021-06-14 10:28
> @roman-orekhov Yes, old app is not compatible with new DLL.
> I might have found the problem, there's incorrect status returned when the lib is partially initialized.
> 
> Could you try the dll with the fixed status. It was returning status 0 rather than correct 2.
> It could still display some sort of an error, but allow the app to load.
> [ZenStates-Core.zip](https://github.com/irusanov/ZenTimings/files/6647586/ZenStates-Core.zip)

Also not start.

**Comment by Vincent-Michael** [comment] 2021-06-14 10:53
confirm

maybe help this:
![Image](https://i.imgur.com/y2zFSAo.png)

**Comment by roman-orekhov** [comment] 2021-06-14 11:01
@Vincent-Michael 
It fails at a later stage for me, when string "CPU" is already shown on UI.

**Comment by CfYz-R** [comment] 2021-06-14 11:42
Same here, unzipped to separate folder, check updates and closes on CPU polling. Debug from working 1.2.3 attached.
[Debug_Report_27061181,5946686_1.2.3.txt](https://github.com/irusanov/ZenTimings/files/6648016/Debug_Report_27061181.5946686_1.2.3.txt)

**Comment by irusanov** [comment] 2021-06-14 12:07
Issue found thanks to the German ZEN community, it's a locale issue.
Will release a fixed version soon.

Thanks for the reports and sorry for the inconvenience.

**Closed** 2021-06-14 12:36 UTC
